### ISSUE TITLE
ModuleNotFoundError: No module named 'ripser'

### ISSUE THREAD

**Issue by jonyscathe** [scikit-tda/ripser.py#171]
Installing ripser==0.6.9 in either a python:3.12.4-slim docker container with poetry or installing with pip in Ubuntu (also Python 3.12.4) I get a ModuleNotFoundError when I try and run `import ripser` or any `from ripser import ripser` or similar imports.

In my poetry environment I can see the ripser-0.6.9.dist-info, but not ripser itself.

'pyRipser.cpython-312-x86_64-linux-gnu.so' is also in the site-packages folder so I can run `import pyRipser` but that only gets me doRipsFiltrationDM and doRipsFiltrationDMSparse.

I don't think I'm doing anything wrong here. Ripser 0.6.8 works fine in the same environment.

**Comment by catanzaromj** [comment]
Thanks for raising this issue. Indeed, the github action for uploading to PyPI was skipped. Sorry about that.

**Comment by catanzaromj** [comment]
Actually, it's a bit more complicated than I initially thought. The issue is (as you say) the `ripser` module not being included with the wheels. I think I put incomplete syntax for specifying `ripser` in the updated `pyproject.toml` file. I will fix this soon. In the meantime, please use `0.6.8`. Sorry again.

**Comment by jonyscathe** [comment]
All good - updating to a new style of packaging is never as straight forward as it should be in Python.

**Comment by catanzaromj** [comment]
@jonyscathe I released v0.6.10 which I hope fixes the problem. Let us know if you have any more issues. Thanks!
