### ISSUE TITLE
DLL load failed

### ISSUE THREAD

**Issue by axelderaismes** [scikit-tda/ripser.py#46]
Hello,
 
I tried to install your Python package Ripser. I succeeded at home with a Python 3.6 32 bits.
I have followed the steps mentionned on https://pypi.org/project/ripser/ :
pip install cython
pip install ripser

Nevertheless, I tried to do exactly the same thing on my work, but each time (with Python 3.6 32 bits and Python 3.6 64 bits), I had the same error : 
 
Traceback (most recent call last):
  File "C:\machine_learning\research\tda_ripser.py", line 3, in <module>
    from ripser import *
  File "C:\Anaconda3_3.6_32\lib\site-packages\ripser\__init__.py", line 1, in <module>
    from .ripser import *
  File "C:\Anaconda3_3.6_32\lib\site-packages\ripser\ripser.py", line 36, in <module>
    from pyRipser import doRipsFiltrationDM as DRFDM
ImportError: DLL load failed: Le module spécifié est introuvable.
 
 
I am wondering if it is not due to a problem of  dependence to a build library like MS build or something else.
 
Any help would be greatly appreciated. Thanks in advance !
Best regards,

Axel

**Comment by sauln** [comment]
Hi Axel, thanks for reaching out.

I am no expert in this, so am a bit out on a limb here. Hopefully we can get this resolved and document the issue so it will help others in the future.

After some google sleuthing it looks like it might be an issue with your paths.  This thread might provide some answers:
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/2f9TNPVzcFI

Another possibility is to try installing with the wheel rather than an egg. I believe all you need to do this is to first run `pip install wheel`, then pip should automatically choose the wheel when searching pypi.  If this doesn't change anything, look at the available files on Pypi (https://pypi.org/project/ripser/#files) and see if one of these fits your system better.  

Please let me know if any of this helps.

**Comment by axelderaismes** [comment]
Hello Nathaniel,

Thanks for your answer.
After investigations, it turned out that I had MinGW at home but not at work (you put me on good tracks by telling me that the problem came from the paths).

These command lines make my script work : 
SET PATH=C:\Anaconda3_32;C:\Anaconda3_32\Scripts;C:\MinGW\bin; & python myscriptwithripser.py

Maybe you could update the setup instructions to explain that MinGW or the equivalent must be installed so as to make the dll work. I am sure it could help future users.

Thanks again for your help!

Axel

**Comment by ctralie** [comment]
Interesting, thanks for the update!  We did indeed compile it with Mingw,
so perhaps it is true that those dlls aren't there by default.  We will
definitely update the instructions.

**Comment by sauln** [comment]
I added a brief blurb in the readme that MinGW is required.  

Thanks again for bringing it to our attention!
