### ISSUE TITLE
Failed building wheel for ripser

### ISSUE THREAD

**Issue by tpilaae** [scikit-tda/ripser.py#47]
Hi! 

I tried to pip install ripser after downloading anaconda. I have very few other programs on this old computer (macOS Sierra). It says "Failed building wheel" in red further down and I am unable to import ripser to any program in anaconda/spyder. Any help is appreciated, thanks in advance!
/Lukas

Here is what the terminal says:

```
pip install ripser
Collecting ripser
  Using cached https://files.pythonhosted.org/packages/20/59/302dab2f1be85f32c57bdf8d4595d0437db76131b13504025abfc8373b03/ripser-0.3.0.tar.gz
Requirement already satisfied: Cython in /anaconda3/lib/python3.7/site-packages (from ripser) (0.28.5)
Requirement already satisfied: numpy in /anaconda3/lib/python3.7/site-packages (from ripser) (1.15.1)
Requirement already satisfied: scipy in /anaconda3/lib/python3.7/site-packages (from ripser) (1.1.0)
Requirement already satisfied: matplotlib in /anaconda3/lib/python3.7/site-packages (from ripser) (2.2.3)
Requirement already satisfied: scikit-learn in /anaconda3/lib/python3.7/site-packages (from ripser) (0.19.2)
Requirement already satisfied: cycler>=0.10 in /anaconda3/lib/python3.7/site-packages (from matplotlib->ripser) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->ripser) (2.2.0)
Requirement already satisfied: python-dateutil>=2.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->ripser) (2.7.3)
Requirement already satisfied: pytz in /anaconda3/lib/python3.7/site-packages (from matplotlib->ripser) (2018.5)
Requirement already satisfied: six>=1.10 in /anaconda3/lib/python3.7/site-packages (from matplotlib->ripser) (1.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /anaconda3/lib/python3.7/site-packages (from matplotlib->ripser) (1.0.1)
Requirement already satisfied: setuptools in /anaconda3/lib/python3.7/site-packages (from kiwisolver>=1.0.1->matplotlib->ripser) (40.2.0)
Building wheels for collected packages: ripser
  Running setup.py bdist_wheel for ripser ... error
  Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-install-wnp2xir0/ripser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-wheel-d5w2gmzx --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/ripser
  copying ripser/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ripser
  copying ripser/_version.py -> build/lib.macosx-10.7-x86_64-3.7/ripser
  copying ripser/ripser.py -> build/lib.macosx-10.7-x86_64-3.7/ripser
  running build_ext
  building 'pyRipser' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/ripser
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DUSE_COEFFICIENTS=1 -DNDEBUG=1 -DASSEMBLE_REDUCTION_MATRIX=1 -I./ripser -I/anaconda3/include/python3.7m -I/anaconda3/lib/python3.7/site-packages/numpy/core/include -c ripser/pyRipser.cpp -o build/temp.macosx-10.7-x86_64-3.7/ripser/pyRipser.o -std=c++11 -Ofast -D_hypot=hypot
  In file included from ripser/pyRipser.cpp:619:
  In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
  In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
  /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it by " \
   ^
  In file included from ripser/pyRipser.cpp:626:
  ./ripser/ripser.cpp:50:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^~~~~~~~~~~~~~~
  1 warning and 1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for ripser
  Running setup.py clean for ripser
Failed to build ripser
Installing collected packages: ripser
  Running setup.py install for ripser ... error
    Complete output from command /anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-install-wnp2xir0/ripser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-record-sy29a5ww/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/ripser
    copying ripser/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ripser
    copying ripser/_version.py -> build/lib.macosx-10.7-x86_64-3.7/ripser
    copying ripser/ripser.py -> build/lib.macosx-10.7-x86_64-3.7/ripser
    running build_ext
    building 'pyRipser' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/ripser
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -DUSE_COEFFICIENTS=1 -DNDEBUG=1 -DASSEMBLE_REDUCTION_MATRIX=1 -I./ripser -I/anaconda3/include/python3.7m -I/anaconda3/lib/python3.7/site-packages/numpy/core/include -c ripser/pyRipser.cpp -o build/temp.macosx-10.7-x86_64-3.7/ripser/pyRipser.o -std=c++11 -Ofast -D_hypot=hypot
    In file included from ripser/pyRipser.cpp:619:
    In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
    In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
    In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
    /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: "Using deprecated NumPy API, disable it by "          "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
    #warning "Using deprecated NumPy API, disable it by " \
     ^
    In file included from ripser/pyRipser.cpp:626:
    ./ripser/ripser.cpp:50:10: fatal error: 'unordered_map' file not found
    #include <unordered_map>
             ^~~~~~~~~~~~~~~
    1 warning and 1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-install-wnp2xir0/ripser/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-record-sy29a5ww/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/0s/5w98_4q16yg4h9vyjmvmwnzm0000gn/T/pip-install-wnp2xir0/ripser/

```

**Comment by ctralie** [comment]
Hello Lukas,
My apologies for the trouble, and thank you for your detailed bug report!  I will do my best to fix this in a timely manner.

My first attempt to fix it doesn't appear to work under Linux, but I'm curious if it works on your setup.  If you get a chance, could you check out the following branch
https://github.com/scikit-tda/ripser.py/tree/macbugfix
Then type

~~~~
python setup.py install
~~~~

Let me know if you still get the same error

**Comment by tpilaae** [comment]
Hi again!

I just downloaded the branch, I simply went into the downloaded folder "ripser.py-macbugfix" and ran the command you suggested. A few red lines showed in the terminal during install (I could post it here if you'd like) but now I can run the "example usage" script from https://ripser.scikit-tda.org/ in spyder! Thank you so much for your quick fix! 

/Lukas

**Comment by ctralie** [comment]
Hmm okay interesting to know.  Yes, please post those lines here if you get the chance.  @sauln I wonder if we'll have to create some kind of conditional compilation with different flags depending on the OS

**Comment by sauln** [comment]
Dang, sorry you're having this trouble @tpilaae.

I've been able to replicate the error in Travis: https://travis-ci.org/scikit-tda/ripser.py/jobs/438824189, and it sounds like the fix @ctralie suggested works for you.  I'll try to set it up so you can install directly from master instead of a special branch.

It looks like you are running MacOS Lion 10.7.  Is this true? I believe Sierra is a much newer version and doesn't have the same problems.

**Comment by tpilaae** [comment]
I'm just glad that I'm getting help! 

@sauln This is an 6 y/o computer so maybe Lion is what was pre-installed but it says in "About this mac" that it is currently macOS Sierra version 10.12.6 (16G1510). 

@ctralie Here are the warnings from the install:

In file included from ripser/pyRipser.cpp:620:
In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:18:
In file included from /anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1823:
/anaconda3/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: 
      "Using deprecated NumPy API, disable it by "          "#defining
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it by " \
 ^
In file included from ripser/pyRipser.cpp:627:
./ripser/ripser.cpp:651:58: warning: comparison of integers of different signs:
      'size_t' (aka 'unsigned long') and 'index_t' (aka 'long long')
      [-Wsign-compare]
  ...= (index_column_to_reduce == index_column_to_add);
        ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
./ripser/ripser.cpp:800:5: note: in instantiation of member function
      'ripser<compressed_distance_matrix<compressed_matrix_layout::LOWER_TRIANGULAR>
      >::compute_pairs' requested here
                                compute_pairs(columns_to_reduce, pivot_c...
                                ^
./ripser/ripser.cpp:1031:5: note: in instantiation of member function
      'ripser<compressed_distance_matrix<compressed_matrix_layout::LOWER_TRIANGULAR>
      >::compute_barcodes' requested here
                r.compute_barcodes();
                  ^
./ripser/ripser.cpp:651:58: warning: comparison of integers of different signs:
      'size_t' (aka 'unsigned long') and 'index_t' (aka 'long long')
      [-Wsign-compare]
  ...= (index_column_to_reduce == index_column_to_add);
        ~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~
./ripser/ripser.cpp:800:5: note: in instantiation of member function
      'ripser<sparse_distance_matrix>::compute_pairs' requested here
                                compute_pairs(columns_to_reduce, pivot_c...
                                ^
./ripser/ripser.cpp:1036:5: note: in instantiation of member function
      'ripser<sparse_distance_matrix>::compute_barcodes' requested here
                r.compute_barcodes();
                  ^
./ripser/ripser.cpp:854:32: warning: private field 'v' is not used
      [-Wunused-private-field]
        index_t idx_below, idx_above, v, k, max_vertex_below;
                                      ^
4 warnings generated.
g++ -bundle -undefined dynamic_lookup -L/anaconda3/lib -arch x86_64 -L/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/ripser/pyRipser.o -o build/lib.macosx-10.7-x86_64-3.7/pyRipser.cpython-37m-darwin.so
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

**Comment by ctralie** [comment]
Well thankfully those warnings aren't so important.  Glad it at least works
for you on this branch

**Comment by tpilaae** [comment]
Nice, your help is much appreciated!

**Comment by ctralie** [comment]
No problem, thanks for bringing this to our attention!

**Comment by sauln** [comment]
@tpilaae Interesting that it says Sierra. In the compiler logs, it says 10.7 (which is lion). An excerpt from the first log is shown here:

```
creating build/lib.macosx-10.7-x86_64-3.7
```

Maybe your compiler are still on 10.7?

**Comment by tpilaae** [comment]
Hi, sorry for the delay. Here is the output from running python in the terminal:

>>> import platform
>>> print(platform.system())
Darwin
>>> print(platform.release())
16.7.0

**Comment by sauln** [comment]
Hi Lukas (@tpilaae),  

I think I've figured out a solution that should work for everybody involved, without having to keep these platform specific fixes on a separate branch.  

Could you please try to install Ripser.py from the macbugfix branch again and let me know if it works for you?

The previous fixes that worked for you broke the installation on all Linux systems. This way should be compatible for all systems.

Thanks!
Nathaniel

**Comment by linnostrom** [comment]
Hi!

I am experiencing exactly the same problem as tpilaae (Failed building wheel for ripser), and I can't access the link https://github.com/scikit-tda/ripser.py/tree/macbugfix. Someone else who is experiencing the same?

**Comment by sauln** [comment]
Hi @linnostrom,  

Sorry about that.

I merged the macbugfix branch into master. It now has a conditional that only modified the compiler flags on a Mac computer.  

Have you tried installing from master branch? If that is not working, then let’s look into it.

**Comment by linnostrom** [comment]
Hi again!

Thank you for looking into this sauln! I tried to install it from the master branch using pip install https://github.com/scikit-tda/ripser.py 

But I get the error code "Cannot unpack file", here is the total output: 
Collecting https://github.com/scikit-tda/ripser.py
  Downloading https://github.com/scikit-tda/ripser.py
     / 122kB 158kB/s
  Cannot unpack file /private/var/folders/m3/mtbsbm5d4vq1ygnm_zf4dy_c0000gn/T/pip-unpack-l1tlgflc/ripser.py (downloaded from /private/var/folders/m3/mtbsbm5d4vq1ygnm_zf4dy_c0000gn/T/pip-req-build-vdefg1lo, content-type: text/html; charset=utf-8); cannot detect archive format
Cannot determine archive format of /private/var/folders/m3/mtbsbm5d4vq1ygnm_zf4dy_c0000gn/T/pip-req-build-vdefg1lo

Thanks! 
Linn

**Comment by jwayland-cads** [comment]
Hi @sauln,

I'm running the latest Mac OS (Monterey) and my default compiler is g++ installed via HomeBrew.

I am also unable to build wheels for ripser, nor am I able to clone the repo and successfully run setup.py

Here are my errors after running `pip install ripser`:
` Building wheel for ripser (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /opt/anaconda3/bin/python /opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/tmpvch1h8_p
       cwd: /private/var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/pip-install-d0ysv8of/ripser_19f650052ef44b17b991e32c95f192a5
  Complete output (104 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-x86_64-3.8
  creating build/lib.macosx-10.9-x86_64-3.8/ripser
  copying ripser/_version.py -> build/lib.macosx-10.9-x86_64-3.8/ripser
  copying ripser/__init__.py -> build/lib.macosx-10.9-x86_64-3.8/ripser
  copying ripser/ripser.py -> build/lib.macosx-10.9-x86_64-3.8/ripser
  running build_ext
  creating build/temp.macosx-10.9-x86_64-3.8
  creating build/temp.macosx-10.9-x86_64-3.8/ripser
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64 -DUSE_COEFFICIENTS=1 -DNDEBUG=1 -DASSEMBLE_REDUCTION_MATRIX=1 -I./ripser -I/opt/anaconda3/include/python3.8 -I/private/var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/pip-build-env-e56dicvz/overlay/lib/python3.8/site-packages/numpy/core/include -c ripser/pyRipser.cpp -o build/temp.macosx-10.9-x86_64-3.8/ripser/pyRipser.o -Ofast -D_hypot=hypot -std=c++11 -mmacosx-version-min=10.9
  In file included from ripser/pyRipser.cpp:738:
  In file included from /private/var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/pip-build-env-e56dicvz/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4:
  In file included from /private/var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/pip-build-env-e56dicvz/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
  In file included from /private/var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/pip-build-env-e56dicvz/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:
  /private/var/folders/1p/m6cskv352lbdcz9_kftkxzjc0000gn/T/pip-build-env-e56dicvz/overlay/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: "Using deprecated NumPy API, disable it with "          "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
  #warning "Using deprecated NumPy API, disable it with " \
   ^
  In file included from ripser/pyRipser.cpp:751:
  In file included from ./ripser/ripser.cpp:43:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: no member named 'signbit' in the global namespace; did you mean 'sigwait'?
  using ::signbit;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:101:5: note: 'sigwait' declared here
  int     sigwait(const sigset_t * __restrict, int * __restrict) __DARWIN_ALIAS_C(sigwait);
          ^
  In file included from ripser/pyRipser.cpp:751:
  In file included from ./ripser/ripser.cpp:43:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: no member named 'fpclassify' in the global namespace
  using ::fpclassify;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: no member named 'isfinite' in the global namespace; did you mean 'finite'?
  using ::isfinite;
        ~~^
  /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:752:12: note: 'finite' declared here
  extern int finite(double)
             ^
  In file included from ripser/pyRipser.cpp:751:
  In file included from ./ripser/ripser.cpp:43:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: no member named 'isinf' in the global namespace
  using ::isinf;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: no member named 'isnan' in the global namespace
  using ::isnan;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: no member named 'isnormal' in the global namespace
  using ::isnormal;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:7: error: no member named 'isgreater' in the global namespace; did you mean '::std::greater'?
  using ::isgreater;
        ^~
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:738:29: note: '::std::greater' declared here
  struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                              ^
  In file included from ripser/pyRipser.cpp:751:
  In file included from ./ripser/ripser.cpp:43:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:7: error: no member named 'isgreaterequal' in the global namespace; did you mean '::std::greater_equal'?
  using ::isgreaterequal;
        ^~
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:767:29: note: '::std::greater_equal' declared here
  struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                              ^
  In file included from ripser/pyRipser.cpp:751:
  In file included from ./ripser/ripser.cpp:43:
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: no member named 'isless' in the global namespace
  using ::isless;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: no member named 'islessequal' in the global namespace
  using ::islessequal;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: no member named 'islessgreater' in the global namespace
  using ::islessgreater;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  /Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: no member named 'isunordered' in the global namespace
  using ::isunordered;
        ~~^
  In file included from ripser/pyRipser.cpp:751:
  ./ripser/ripser.cpp:163:1: warning: attribute '__packed__' is ignored, place it after "struct" to apply attribute to type declaration [-Wignored-attributes]
  PACK(struct entry_t {
  ^
  ./ripser/ripser.cpp:160:36: note: expanded from macro 'PACK'
  #define PACK( ... ) __attribute__((__packed__)) __VA_ARGS__
                                     ^
  ripser/pyRipser.cpp:6940:16: warning: absolute value function 'abs' given an argument of type 'const Py_ssize_t' (aka 'const long') but has parameter of type 'int' which may cause truncation of value [-Wabsolute-value]
      if (likely(__Pyx_sst_abs(size) <= 1)) {
                 ^
  ripser/pyRipser.cpp:786:34: note: expanded from macro '__Pyx_sst_abs'
      #define __Pyx_sst_abs(value) std::abs(value)
                                   ^
  ripser/pyRipser.cpp:6940:16: note: use function 'std::abs' instead
  ripser/pyRipser.cpp:786:34: note: expanded from macro '__Pyx_sst_abs'
      #define __Pyx_sst_abs(value) std::abs(value)
                                   ^
  ripser/pyRipser.cpp:6940:16: note: include the header <cstdlib> or explicitly provide a declaration for 'std::abs'
  ripser/pyRipser.cpp:786:34: note: expanded from macro '__Pyx_sst_abs'
      #define __Pyx_sst_abs(value) std::abs(value)
                                   ^
  3 warnings and 13 errors generated.
  error: command '/usr/bin/gcc' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for ripser
Failed to build ripser
ERROR: Could not build wheels for ripser, which is required to install pyproject.toml-based projects`



And here are my errors after running `python setup.py install`


`Compiling ripser/pyRipser.pyx because it depends on /opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.pxd.
[1/1] Cythonizing ripser/pyRipser.pyx
/opt/anaconda3/lib/python3.8/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /Users/jeremywayland/Desktop/Coursework/CS 613/Homework/PersistentHomologyKNN/src/ripser.py/ripser/pyRipser.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
running install
/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/setuptools/command/easy_install.py:156: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/opt/anaconda3/lib/python3.8/site-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 4.0.0-unsupported is an invalid version and will not be supported in a future release
  warnings.warn(
running bdist_egg
running egg_info
writing manifest file 'ripser.egg-info/SOURCES.txt'
running install_lib
running build_py
running build_ext
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/opt/anaconda3/include -arch x86_64 -I/opt/anaconda3/include -arch x86_64 -DUSE_COEFFICIENTS=1 -DNDEBUG=1 -DASSEMBLE_REDUCTION_MATRIX=1 -I./ripser -I/opt/anaconda3/include/python3.8 -I/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -c ripser/pyRipser.cpp -o build/temp.macosx-10.9-x86_64-3.8/ripser/pyRipser.o -Ofast -D_hypot=hypot -std=c++11 -mmacosx-version-min=10.9
In file included from ripser/pyRipser.cpp:667:
In file included from /opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/arrayobject.h:4:
In file included from /opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/ndarrayobject.h:12:
In file included from /opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969:
/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: 
      "Using deprecated NumPy API, disable it with "          "#define
      NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-W#warnings]
#warning "Using deprecated NumPy API, disable it with " \
 ^
In file included from ripser/pyRipser.cpp:680:
In file included from ./ripser/ripser.cpp:43:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:317:9: error: 
      no member named 'signbit' in the global namespace; did you mean 'sigwait'?
using ::signbit;
      ~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/signal.h:101:5: note: 
      'sigwait' declared here
int     sigwait(const sigset_t * __restrict, int * __restrict) __DARWIN_...
        ^
In file included from ripser/pyRipser.cpp:680:
In file included from ./ripser/ripser.cpp:43:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:318:9: error: 
      no member named 'fpclassify' in the global namespace
using ::fpclassify;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:319:9: error: 
      no member named 'isfinite' in the global namespace; did you mean 'finite'?
using ::isfinite;
      ~~^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/math.h:752:12: note: 
      'finite' declared here
extern int finite(double)
           ^
In file included from ripser/pyRipser.cpp:680:
In file included from ./ripser/ripser.cpp:43:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:320:9: error: 
      no member named 'isinf' in the global namespace
using ::isinf;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:321:9: error: 
      no member named 'isnan' in the global namespace
using ::isnan;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:322:9: error: 
      no member named 'isnormal' in the global namespace
using ::isnormal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:323:7: error: 
      no member named 'isgreater' in the global namespace; did you mean
      '::std::greater'?
using ::isgreater;
      ^~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:738:29: note: 
      '::std::greater' declared here
struct _LIBCPP_TEMPLATE_VIS greater : binary_function<_Tp, _Tp, bool>
                            ^
In file included from ripser/pyRipser.cpp:680:
In file included from ./ripser/ripser.cpp:43:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:324:7: error: 
      no member named 'isgreaterequal' in the global namespace; did you mean
      '::std::greater_equal'?
using ::isgreaterequal;
      ^~
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/functional:767:29: note: 
      '::std::greater_equal' declared here
struct _LIBCPP_TEMPLATE_VIS greater_equal : binary_function<_Tp, _Tp, bool>
                            ^
In file included from ripser/pyRipser.cpp:680:
In file included from ./ripser/ripser.cpp:43:
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:325:9: error: 
      no member named 'isless' in the global namespace
using ::isless;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:326:9: error: 
      no member named 'islessequal' in the global namespace
using ::islessequal;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:327:9: error: 
      no member named 'islessgreater' in the global namespace
using ::islessgreater;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:328:9: error: 
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/cmath:329:9: error: 
      no member named 'isunordered' in the global namespace
using ::isunordered;
      ~~^
In file included from ripser/pyRipser.cpp:680:
./ripser/ripser.cpp:163:1: warning: attribute '__packed__' is ignored, place it
      after "struct" to apply attribute to type declaration
      [-Wignored-attributes]
PACK(struct entry_t {
^
./ripser/ripser.cpp:160:36: note: expanded from macro 'PACK'
#define PACK( ... ) __attribute__((__packed__)) __VA_ARGS__
                                   ^
ripser/pyRipser.cpp:6824:16: warning: absolute value function 'abs' given an
      argument of type 'const Py_ssize_t' (aka 'const long') but has parameter
      of type 'int' which may cause truncation of value [-Wabsolute-value]
    if (likely(__Pyx_sst_abs(size) <= 1)) {
               ^
ripser/pyRipser.cpp:715:34: note: expanded from macro '__Pyx_sst_abs'
    #define __Pyx_sst_abs(value) std::abs(value)
                                 ^
ripser/pyRipser.cpp:6824:16: note: use function 'std::abs' instead
ripser/pyRipser.cpp:715:34: note: expanded from macro '__Pyx_sst_abs'
    #define __Pyx_sst_abs(value) std::abs(value)
                                 ^
ripser/pyRipser.cpp:6824:16: note: include the header <cstdlib> or explicitly
      provide a declaration for 'std::abs'
ripser/pyRipser.cpp:715:34: note: expanded from macro '__Pyx_sst_abs'
    #define __Pyx_sst_abs(value) std::abs(value)
                                 ^
3 warnings and 13 errors generated.
error: command '/usr/bin/gcc' failed with exit code 1`
